# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42192999e6267be39ad99fd5efd78fb68ebe82e37a2007ae106b2c47fb715915428994ed1ff91d6cd66fdd0b4ff5441c9acb92c21ece8adcdfc66ff1e161e498

test:
  secret_key_base: 7d9394360ed03a11a7f23ad4892c7b7ec9a5b68ab46ebacf5021542052be33ca9d1361eec97f03a2d8c44ab6e3b4a422254578aec85ccf7543d7b97f3f2be797

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
